import logging
from datetime import UTC, datetime, timedelta

from canwxlab_api.adapters.base import BBox, WeatherSourceAdapter
from canwxlab_api.models import (
    AlertFeature,
    ConfidenceLevel,
    DataSource,
    LayerServiceType,
    Observation,
    SourceAdapterRef,
    SourceStatus,
    SpatiotemporalEvent,
    TruthMode,
    WeatherLayer,
)

logger = logging.getLogger(__name__)

try:
    import h3

    def _h3_cell(lat: float, lng: float, resolution: int = 5) -> str:
        return h3.latlng_to_cell(lat, lng, resolution)
except ImportError:
    logger.warning("h3 library not available; h3_cell will be empty on mock events")

    def _h3_cell(lat: float, lng: float, resolution: int = 5) -> str:
        _ = lat, lng, resolution
        return ""

NOW = datetime(2026, 5, 15, 12, 0, tzinfo=UTC)
MOCK_ATTRIBUTION = "Synthetic sample data generated by CanWxLab."


class MockWeatherSourceAdapter(WeatherSourceAdapter):
    """Deterministic sample data for offline development and tests."""

    async def list_sources(self) -> list[DataSource]:
        return [
            DataSource(
                source_id="mock_canwxlab",
                name="CanWxLab Mock Weather Feed",
                status=SourceStatus.mock,
                adapter="mock",
                last_updated=NOW,
                last_successful_fetch=NOW,
                last_attempted_fetch=NOW,
                retrieved_at=NOW,
                expires_at=NOW + timedelta(hours=24),
                attribution=MOCK_ATTRIBUTION,
                description="Offline deterministic data used to exercise UI and API contracts.",
                message="Operating in deterministic mock/offline mode.",
                is_live=False,
            )
        ]

    async def list_layers(self) -> list[WeatherLayer]:
        return [
            WeatherLayer(
                layer_id="mock_temperature",
                name="Mock Temperature",
                title="Mock Temperature",
                kind="raster",
                variable="temperature_2m",
                unit="degC",
                source_id="mock_canwxlab",
                status=SourceStatus.mock,
                adapter="mock",
                service_type=LayerServiceType.mock,
                last_updated=NOW,
                last_successful_fetch=NOW,
                last_attempted_fetch=NOW,
                retrieved_at=NOW,
                expires_at=NOW + timedelta(hours=24),
                attribution=MOCK_ATTRIBUTION,
                default_opacity=0.72,
                color_ramps=["thermal", "viridis", "blue_red", "turbo"],
                description="Generated Canada-wide temperature-like field for UI development.",
                message="Synthetic raster field.",
            ),
            WeatherLayer(
                layer_id="mock_wind",
                name="Mock Wind Vectors",
                title="Mock Wind Vectors",
                kind="vector",
                variable="wind_10m",
                unit="m/s",
                source_id="mock_canwxlab",
                status=SourceStatus.mock,
                adapter="mock",
                service_type=LayerServiceType.mock,
                last_updated=NOW,
                last_successful_fetch=NOW,
                last_attempted_fetch=NOW,
                retrieved_at=NOW,
                expires_at=NOW + timedelta(hours=24),
                attribution=MOCK_ATTRIBUTION,
                default_opacity=0.85,
                color_ramps=["wind", "blue_red"],
                description="Generated wind vector field for deck.gl overlay development.",
                message="Synthetic vector field.",
            ),
            WeatherLayer(
                layer_id="mock_radar",
                name="Mock Radar Precipitation",
                title="Mock Radar Precipitation",
                kind="raster",
                variable="precipitation_rate",
                unit="mm/h",
                source_id="mock_canwxlab",
                status=SourceStatus.mock,
                adapter="mock",
                service_type=LayerServiceType.mock,
                last_updated=NOW,
                last_successful_fetch=NOW,
                last_attempted_fetch=NOW,
                retrieved_at=NOW,
                expires_at=NOW + timedelta(hours=24),
                attribution=MOCK_ATTRIBUTION,
                default_opacity=0.64,
                color_ramps=["precipitation", "turbo", "viridis"],
                description="Generated precipitation bands resembling radar returns.",
                message="Synthetic raster field.",
            ),
            WeatherLayer(
                layer_id="mock_stations",
                name="Mock Station Observations",
                title="Mock Station Observations",
                kind="point",
                variable="surface_observations",
                unit="mixed",
                source_id="mock_canwxlab",
                status=SourceStatus.mock,
                adapter="mock",
                service_type=LayerServiceType.mock,
                last_updated=NOW,
                last_successful_fetch=NOW,
                last_attempted_fetch=NOW,
                retrieved_at=NOW,
                expires_at=NOW + timedelta(hours=24),
                attribution=MOCK_ATTRIBUTION,
                default_opacity=1.0,
                color_ramps=["thermal"],
                description="Sample observation stations in Canadian cities.",
                message="Synthetic point observations.",
            ),
            WeatherLayer(
                layer_id="mock_alerts",
                name="Mock Weather Alerts",
                title="Mock Weather Alerts",
                kind="polygon",
                variable="alerts",
                unit="category",
                source_id="mock_canwxlab",
                status=SourceStatus.mock,
                adapter="mock",
                service_type=LayerServiceType.mock,
                last_updated=NOW,
                last_successful_fetch=NOW,
                last_attempted_fetch=NOW,
                retrieved_at=NOW,
                expires_at=NOW + timedelta(hours=24),
                attribution=MOCK_ATTRIBUTION,
                default_opacity=0.58,
                color_ramps=["alert_severity"],
                description="Sample alert polygons. Not official warnings.",
                message="Synthetic alert polygons.",
            ),
            WeatherLayer(
                layer_id="canwxsim_output",
                name="CanWxSim Output",
                title="CanWxSim Output",
                kind="simulation",
                variable="simulation_fields",
                unit="mixed",
                source_id="mock_canwxlab",
                status=SourceStatus.mock,
                adapter="mock",
                service_type=LayerServiceType.generated,
                last_updated=NOW,
                last_successful_fetch=NOW,
                last_attempted_fetch=NOW,
                retrieved_at=NOW,
                expires_at=NOW + timedelta(hours=24),
                attribution="Experimental CanWxSim sample output.",
                default_opacity=0.7,
                color_ramps=["simulation", "thermal", "precipitation"],
                description=(
                    "Experimental 2D sandbox simulation output. "
                    "Not an operational forecast."
                ),
                is_experimental=True,
                message="Experimental simulation layer.",
            ),
        ]

    async def get_layer_metadata(self, layer_id: str) -> WeatherLayer | None:
        layers = await self.list_layers()
        return next((layer for layer in layers if layer.layer_id == layer_id), None)

    async def fetch_recent_hourly_observations(
        self, bbox: BBox | None = None, limit: int = 100
    ) -> list[Observation]:
        observations = await self.fetch_station_observations(bbox=bbox, limit=limit)
        return [
            observation.model_copy(
                update={
                    "observation_id": f"mock-hourly-{observation.station_id}-{NOW.isoformat()}",
                    "quality_flags": [*observation.quality_flags, "hourly_mock"],
                }
            )
            for observation in observations
        ]

    async def fetch_station_observations(
        self, bbox: BBox | None = None, limit: int = 100
    ) -> list[Observation]:
        stations = [
            ("CYEG", "Edmonton Intl", 53.3097, -113.5797, 723.0, 13.4, 6.2, 1011.2),
            ("CYYC", "Calgary Intl", 51.1215, -114.0076, 1084.0, 15.1, 8.5, 1008.5),
            ("CYVR", "Vancouver Intl", 49.1951, -123.1779, 4.0, 11.2, 5.0, 1016.1),
            ("CYYZ", "Toronto Pearson", 43.6777, -79.6248, 173.0, 18.8, 4.6, 1013.0),
            ("CYFB", "Iqaluit", 63.7564, -68.5558, 34.0, -1.5, 7.1, 1006.4),
            ("CYHZ", "Halifax Stanfield", 44.8808, -63.5086, 145.0, 9.7, 9.2, 1009.3),
        ]
        observations = [
            Observation(
                observation_id=f"mock-{station_id}-{NOW.isoformat()}",
                station_id=station_id,
                station_name=name,
                latitude=lat,
                longitude=lon,
                elevation_m=elevation,
                observed_at=NOW,
                values={"temperature_2m": temp, "wind_speed_10m": wind, "pressure_msl": pressure},
                units={"temperature_2m": "degC", "wind_speed_10m": "m/s", "pressure_msl": "hPa"},
                source_id="mock_canwxlab",
                source_status=SourceStatus.mock,
                adapter="mock",
                quality_flags=["mock"],
                retrieved_at=NOW,
            )
            for station_id, name, lat, lon, elevation, temp, wind, pressure in stations
        ]
        filtered = [
            item for item in observations if _point_in_bbox(item.longitude, item.latitude, bbox)
        ]
        return filtered[: max(1, limit)]

    async def emit_events(
        self, bbox: BBox | None = None, limit: int = 500
    ) -> list[SpatiotemporalEvent]:
        observations = await self.fetch_station_observations(bbox=bbox, limit=limit)
        events: list[SpatiotemporalEvent] = []
        source_ref = SourceAdapterRef(
            adapter_id="mock",
            adapter_version="0.1.0",
        )

        for obs in observations:
            h3_cell = _h3_cell(obs.latitude, obs.longitude, 5)
            for var, val in obs.values.items():
                unit = obs.units.get(var, "")
                events.append(
                    SpatiotemporalEvent(
                        event_kind="meteorological.observation",
                        valid_from=obs.observed_at,
                        observed_at=obs.observed_at,
                        longitude=obs.longitude,
                        latitude=obs.latitude,
                        elevation_m=obs.elevation_m,
                        h3_cell=h3_cell,
                        variable=var,
                        value=val,
                        unit=unit,
                        source_id="mock_canwxlab",
                        source_adapter=source_ref,
                        confidence=0.3,
                        confidence_level=ConfidenceLevel.synthetic,
                        truth_mode=TruthMode.hypothetical,
                        attribution="Synthetic sample data generated by CanWxLab.",
                        raw_properties={
                            "station_id": obs.station_id,
                            "station_name": obs.station_name,
                            "quality_flags": obs.quality_flags,
                        },
                    )
                )
        return events

    async def fetch_alerts(self, bbox: BBox | None = None, limit: int = 100) -> list[AlertFeature]:
        alerts = [
            AlertFeature(
                alert_id="mock-alert-prairie-wind",
                source_id="mock_canwxlab",
                source_status=SourceStatus.mock,
                adapter="mock",
                event="Strong wind watch",
                severity="moderate",
                headline="Mock strong wind watch for central Alberta",
                description=(
                    "Synthetic alert polygon for UI testing. "
                    "This is not an official ECCC warning."
                ),
                issued_at=NOW - timedelta(hours=1),
                expires_at=NOW + timedelta(hours=5),
                geometry={
                    "type": "Polygon",
                    "coordinates": [
                        [
                            [-115.8, 52.1],
                            [-111.2, 52.1],
                            [-111.2, 54.4],
                            [-115.8, 54.4],
                            [-115.8, 52.1],
                        ]
                    ],
                },
                attribution=MOCK_ATTRIBUTION,
                retrieved_at=NOW,
            ),
            AlertFeature(
                alert_id="mock-alert-atlantic-rain",
                source_id="mock_canwxlab",
                source_status=SourceStatus.mock,
                adapter="mock",
                event="Heavy rainfall statement",
                severity="minor",
                headline="Mock rainfall statement for Nova Scotia",
                description=(
                    "Synthetic alert polygon for UI testing. "
                    "This is not an official ECCC warning."
                ),
                issued_at=NOW - timedelta(hours=2),
                expires_at=NOW + timedelta(hours=8),
                geometry={
                    "type": "Polygon",
                    "coordinates": [
                        [
                            [-65.5, 43.6],
                            [-61.4, 43.6],
                            [-61.4, 46.3],
                            [-65.5, 46.3],
                            [-65.5, 43.6],
                        ]
                    ],
                },
                attribution=MOCK_ATTRIBUTION,
                retrieved_at=NOW,
            ),
        ]
        filtered = [item for item in alerts if _feature_intersects_bbox(item.geometry, bbox)]
        return filtered[: max(1, limit)]


def _point_in_bbox(longitude: float, latitude: float, bbox: BBox | None) -> bool:
    if bbox is None:
        return True
    west, south, east, north = bbox
    return west <= longitude <= east and south <= latitude <= north


def _feature_intersects_bbox(geometry: dict, bbox: BBox | None) -> bool:
    if bbox is None:
        return True
    coordinates = geometry.get("coordinates")
    if not coordinates:
        return False

    flat_points: list[tuple[float, float]] = []

    def collect(points: list) -> None:
        for value in points:
            if isinstance(value, (list, tuple)) and len(value) == 2 and all(
                isinstance(part, (int, float)) for part in value
            ):
                flat_points.append((float(value[0]), float(value[1])))
            elif isinstance(value, list):
                collect(value)

    collect(coordinates)

    if not flat_points:
        return False

    west, south, east, north = bbox
    min_lon = min(point[0] for point in flat_points)
    max_lon = max(point[0] for point in flat_points)
    min_lat = min(point[1] for point in flat_points)
    max_lat = max(point[1] for point in flat_points)

    return not (max_lon < west or min_lon > east or max_lat < south or min_lat > north)
