import type { AlertFeature, DataSource, Observation, WeatherLayer } from "../types/weather";

const now = new Date("2026-05-15T12:00:00Z").toISOString();

export const fallbackSources: DataSource[] = [
  {
    source_id: "mock_canwxlab",
    name: "CanWxLab Mock Weather Feed",
    status: "mock",
    adapter: "mock",
    last_updated: now,
    last_successful_fetch: now,
    last_attempted_fetch: now,
    retrieved_at: now,
    expires_at: now,
    attribution: "Synthetic sample data generated by CanWxLab.",
    description: "Offline fallback source used when the API is not running.",
    message: "Frontend fallback mode active.",
    is_live: false,
    is_experimental: false,
    metadata: {}
  },
  {
    source_id: "eccc_geomet_ogc_api",
    name: "ECCC/MSC GeoMet OGC API",
    status: "unavailable",
    adapter: "eccc_geomet",
    last_updated: null,
    last_successful_fetch: null,
    last_attempted_fetch: null,
    retrieved_at: null,
    expires_at: null,
    attribution: "Environment and Climate Change Canada / Meteorological Service of Canada.",
    license_url: "https://eccc-msc.github.io/open-data/readme_en/",
    homepage_url: "https://api.weather.gc.ca",
    description: "Public Canadian weather and climate OGC API endpoints.",
    message: "API unavailable in frontend fallback mode.",
    error_type: "ApiUnavailable",
    is_live: false,
    is_experimental: false,
    metadata: {}
  },
  {
    source_id: "eccc_geomet_wms",
    name: "ECCC/MSC GeoMet WMS",
    status: "unavailable",
    adapter: "eccc_geomet",
    last_updated: null,
    last_successful_fetch: null,
    last_attempted_fetch: null,
    retrieved_at: null,
    expires_at: null,
    attribution: "Environment and Climate Change Canada / Meteorological Service of Canada.",
    license_url: "https://eccc-msc.github.io/open-data/readme_en/",
    homepage_url: "https://geo.weather.gc.ca/geomet",
    description: "GeoMet WMS capabilities for radar/satellite raster layers.",
    message: "Capabilities unavailable in frontend fallback mode.",
    error_type: "ApiUnavailable",
    is_live: false,
    is_experimental: false,
    metadata: {}
  }
];

function baseLayer(overrides: Partial<WeatherLayer> & Pick<WeatherLayer, "layer_id" | "name" | "kind" | "variable" | "unit" | "source_id" | "description">): WeatherLayer {
  return {
    title: overrides.name,
    status: "mock",
    adapter: "mock",
    service_type: "mock",
    last_updated: now,
    last_successful_fetch: now,
    last_attempted_fetch: now,
    retrieved_at: now,
    expires_at: now,
    attribution: "Synthetic sample data generated by CanWxLab.",
    message: "Frontend fallback layer metadata.",
    error_type: null,
    default_opacity: 0.7,
    color_ramps: ["default"],
    styles: ["default"],
    wms_base_url: null,
    wms_layer_name: null,
    time_dimension_supported: false,
    legend_url: null,
    min_zoom: null,
    max_zoom: null,
    update_frequency_hint: null,
    is_live: false,
    is_experimental: false,
    metadata: {},
    ...overrides
  };
}

export const fallbackLayers: WeatherLayer[] = [
  baseLayer({
    layer_id: "mock_temperature",
    name: "Mock Temperature",
    kind: "raster",
    variable: "temperature_2m",
    unit: "degC",
    source_id: "mock_canwxlab",
    default_opacity: 0.72,
    color_ramps: ["thermal", "viridis", "blue_red", "turbo"],
    description: "Generated Canada-wide temperature-like field for UI development."
  }),
  baseLayer({
    layer_id: "mock_wind",
    name: "Mock Wind Vectors",
    kind: "vector",
    variable: "wind_10m",
    unit: "m/s",
    source_id: "mock_canwxlab",
    default_opacity: 0.85,
    color_ramps: ["wind", "blue_red"],
    description: "Generated wind vector field for deck.gl overlay development."
  }),
  baseLayer({
    layer_id: "mock_radar",
    name: "Mock Radar Precipitation",
    kind: "raster",
    variable: "precipitation_rate",
    unit: "mm/h",
    source_id: "mock_canwxlab",
    default_opacity: 0.64,
    color_ramps: ["precipitation", "turbo", "viridis"],
    description: "Generated precipitation bands resembling radar returns."
  }),
  baseLayer({
    layer_id: "mock_stations",
    name: "Mock Station Observations",
    kind: "point",
    variable: "surface_observations",
    unit: "mixed",
    source_id: "mock_canwxlab",
    default_opacity: 1,
    color_ramps: ["thermal"],
    description: "Sample observation stations in Canadian cities."
  }),
  baseLayer({
    layer_id: "mock_alerts",
    name: "Mock Weather Alerts",
    kind: "polygon",
    variable: "alerts",
    unit: "category",
    source_id: "mock_canwxlab",
    default_opacity: 0.58,
    color_ramps: ["alert_severity"],
    description: "Sample alert polygons. Not official warnings."
  }),
  baseLayer({
    layer_id: "canwxsim_output",
    name: "CanWxSim Output",
    kind: "simulation",
    variable: "simulation_fields",
    unit: "mixed",
    source_id: "mock_canwxlab",
    service_type: "generated",
    default_opacity: 0.7,
    color_ramps: ["simulation", "thermal", "precipitation"],
    description: "Experimental 2D sandbox simulation output. Not an operational forecast.",
    is_experimental: true,
    message: "Experimental simulation layer."
  }),
  baseLayer({
    layer_id: "eccc_weather_alerts",
    name: "ECCC Weather Alerts",
    kind: "polygon",
    variable: "alerts",
    unit: "category",
    source_id: "eccc_geomet_ogc_api",
    status: "unavailable",
    adapter: "eccc_geomet",
    service_type: "ogc_api",
    attribution: "Environment and Climate Change Canada / Meteorological Service of Canada.",
    message: "Live source unavailable in frontend fallback mode.",
    default_opacity: 0.58,
    color_ramps: ["alert_severity"],
    description: "Official ECCC alert polygons via GeoMet OGC API.",
    retrieved_at: null,
    expires_at: null,
    last_updated: null,
    last_successful_fetch: null,
    last_attempted_fetch: null
  }),
  baseLayer({
    layer_id: "eccc_climate_stations",
    name: "ECCC Climate Stations",
    kind: "point",
    variable: "surface_observations",
    unit: "mixed",
    source_id: "eccc_geomet_ogc_api",
    status: "unavailable",
    adapter: "eccc_geomet",
    service_type: "ogc_api",
    attribution: "Environment and Climate Change Canada / Meteorological Service of Canada.",
    message: "Live source unavailable in frontend fallback mode.",
    default_opacity: 1,
    color_ramps: ["thermal"],
    description: "ECCC climate station point features.",
    retrieved_at: null,
    expires_at: null,
    last_updated: null,
    last_successful_fetch: null,
    last_attempted_fetch: null
  }),
  baseLayer({
    layer_id: "eccc_radar_1km_rrai",
    name: "ECCC Radar - Rain Rate (1 km)",
    kind: "raster",
    variable: "radar",
    unit: "mm/h",
    source_id: "eccc_geomet_wms",
    status: "stale",
    adapter: "eccc_geomet",
    service_type: "wms",
    attribution: "Environment and Climate Change Canada / Meteorological Service of Canada.",
    message: "Direct GeoMet WMS fallback using documented layer id; API verification unavailable.",
    default_opacity: 0.82,
    color_ramps: [],
    styles: ["RADARURPPRECIPR14-LINEAR"],
    wms_base_url: "https://geo.weather.gc.ca/geomet",
    wms_layer_name: "RADAR_1KM_RRAI",
    time_dimension_supported: true,
    description: "ECCC North American radar precipitation rate for rain via MSC GeoMet WMS.",
    retrieved_at: null,
    expires_at: null,
    last_updated: null,
    last_successful_fetch: null,
    last_attempted_fetch: null,
    metadata: {
      curated: true,
      verified_runtime: false,
      intended_product_type: "radar",
      candidate_layer_names: ["RADAR_1KM_RRAI"],
      keywords: ["radar"],
    }
  }),
  baseLayer({
    layer_id: "eccc_gdps_p_msl",
    name: "ECCC GDPS - Mean Sea Level Pressure",
    kind: "raster",
    variable: "pressure_msl",
    unit: "hPa",
    source_id: "eccc_geomet_wms",
    status: "stale",
    adapter: "eccc_geomet",
    service_type: "wms",
    attribution: "Environment and Climate Change Canada / Meteorological Service of Canada.",
    message: "Direct GeoMet WMS fallback using documented GDPS MSLP layer id; API verification unavailable.",
    default_opacity: 0.62,
    color_ramps: ["pressure"],
    styles: [],
    wms_base_url: "https://geo.weather.gc.ca/geomet",
    wms_layer_name: "GDPS.DIAG_PN",
    time_dimension_supported: true,
    description: "Global Deterministic Prediction System mean sea level pressure via MSC GeoMet WMS.",
    retrieved_at: null,
    expires_at: null,
    last_updated: null,
    last_successful_fetch: null,
    last_attempted_fetch: null,
    metadata: {
      curated: true,
      verified_runtime: false,
      intended_product_type: "model",
      candidate_layer_names: ["GDPS.DIAG_PN"],
      keywords: ["pressure", "mslp", "model"],
    }
  }),
  baseLayer({
    layer_id: "eccc_goes_east_natural",
    name: "ECCC GOES-East - Natural Colour",
    kind: "raster",
    variable: "satellite",
    unit: "reflectance",
    source_id: "eccc_geomet_wms",
    status: "stale",
    adapter: "eccc_geomet",
    service_type: "wms",
    attribution: "Environment and Climate Change Canada / NOAA.",
    message: "Direct GeoMet WMS fallback using documented layer id; API verification unavailable.",
    default_opacity: 0.78,
    color_ramps: [],
    styles: [],
    wms_base_url: "https://geo.weather.gc.ca/geomet",
    wms_layer_name: "GOES-East_1km_NaturalColor",
    time_dimension_supported: true,
    description: "GOES-East natural colour satellite imagery via MSC GeoMet WMS.",
    retrieved_at: null,
    expires_at: null,
    last_updated: null,
    last_successful_fetch: null,
    last_attempted_fetch: null,
    metadata: {
      curated: true,
      verified_runtime: false,
      intended_product_type: "satellite",
      candidate_layer_names: ["GOES-East_1km_NaturalColor"],
      keywords: ["satellite", "cloud"],
    }
  }),
  baseLayer({
    layer_id: "eccc_goes_east_cloud_type",
    name: "ECCC GOES-East - Day Cloud Type / Night Microphysics",
    kind: "raster",
    variable: "cloud",
    unit: "classification",
    source_id: "eccc_geomet_wms",
    status: "stale",
    adapter: "eccc_geomet",
    service_type: "wms",
    attribution: "Environment and Climate Change Canada / NOAA.",
    message: "Direct GeoMet WMS fallback using documented layer id; API verification unavailable.",
    default_opacity: 0.72,
    color_ramps: [],
    styles: [],
    wms_base_url: "https://geo.weather.gc.ca/geomet",
    wms_layer_name: "GOES-East_1km_DayCloudType-NightMicrophysics",
    time_dimension_supported: true,
    description: "GOES-East cloud type / night microphysics satellite product via MSC GeoMet WMS.",
    retrieved_at: null,
    expires_at: null,
    last_updated: null,
    last_successful_fetch: null,
    last_attempted_fetch: null,
    metadata: {
      curated: true,
      verified_runtime: false,
      intended_product_type: "cloud",
      candidate_layer_names: ["GOES-East_1km_DayCloudType-NightMicrophysics"],
      keywords: ["satellite", "cloud"],
    }
  })
];

export const fallbackObservations: Observation[] = [
  {
    observation_id: "fallback-cyeg",
    station_id: "CYEG",
    station_name: "Edmonton Intl",
    latitude: 53.3097,
    longitude: -113.5797,
    elevation_m: 723,
    observed_at: now,
    values: { temperature_2m: 13.4, wind_speed_10m: 6.2, pressure_msl: 1011.2 },
    units: { temperature_2m: "degC", wind_speed_10m: "m/s", pressure_msl: "hPa" },
    source_id: "mock_canwxlab",
    source_status: "mock",
    adapter: "mock",
    quality_flags: ["mock"],
    retrieved_at: now,
    expires_at: null,
    raw_properties: {}
  },
  {
    observation_id: "fallback-cyyc",
    station_id: "CYYC",
    station_name: "Calgary Intl",
    latitude: 51.1215,
    longitude: -114.0076,
    elevation_m: 1084,
    observed_at: now,
    values: { temperature_2m: 15.1, wind_speed_10m: 8.5, pressure_msl: 1008.5 },
    units: { temperature_2m: "degC", wind_speed_10m: "m/s", pressure_msl: "hPa" },
    source_id: "mock_canwxlab",
    source_status: "mock",
    adapter: "mock",
    quality_flags: ["mock"],
    retrieved_at: now,
    expires_at: null,
    raw_properties: {}
  },
  {
    observation_id: "fallback-cyvr",
    station_id: "CYVR",
    station_name: "Vancouver Intl",
    latitude: 49.1951,
    longitude: -123.1779,
    elevation_m: 4,
    observed_at: now,
    values: { temperature_2m: 11.2, wind_speed_10m: 5.0, pressure_msl: 1016.1 },
    units: { temperature_2m: "degC", wind_speed_10m: "m/s", pressure_msl: "hPa" },
    source_id: "mock_canwxlab",
    source_status: "mock",
    adapter: "mock",
    quality_flags: ["mock"],
    retrieved_at: now,
    expires_at: null,
    raw_properties: {}
  }
];

export const fallbackAlerts: AlertFeature[] = [
  {
    alert_id: "fallback-alert-prairie-wind",
    source_id: "mock_canwxlab",
    source_status: "mock",
    adapter: "mock",
    event: "Strong wind watch",
    severity: "moderate",
    status: "actual",
    headline: "Mock strong wind watch for central Alberta",
    description: "Synthetic alert polygon for UI testing. This is not an official ECCC warning.",
    issued_at: now,
    expires_at: null,
    attribution: "Synthetic sample data generated by CanWxLab.",
    retrieved_at: now,
    raw_properties: {},
    geometry: {
      type: "Polygon",
      coordinates: [[[-115.8, 52.1], [-111.2, 52.1], [-111.2, 54.4], [-115.8, 54.4], [-115.8, 52.1]]]
    }
  }
];

export interface LayerControlState {
  visible: boolean;
  opacity: number;
  colorRamp: string;
}

export function createInitialLayerState(layers: WeatherLayer[]): Record<string, LayerControlState> {
  const hasLiveAlerts = layers.some((layer) => layer.layer_id === "eccc_weather_alerts");
  const hasLiveStations = layers.some((layer) => layer.layer_id === "eccc_climate_stations");

  return Object.fromEntries(
    layers.map((layer) => {
      const visible =
        layer.layer_id === "mock_temperature" ||
        layer.layer_id === "mock_wind" ||
        layer.layer_id === "canwxsim_output" ||
        (layer.layer_id === "eccc_weather_alerts" && layer.status !== "unavailable") ||
        (layer.layer_id === "mock_alerts" && !hasLiveAlerts) ||
        (layer.layer_id === "eccc_climate_stations" && layer.status !== "unavailable") ||
        (layer.layer_id === "mock_stations" && !hasLiveStations);

      return [
        layer.layer_id,
        {
          visible,
          opacity: layer.default_opacity,
          colorRamp: layer.color_ramps[0] ?? "default"
        }
      ];
    })
  );
}

export function sampleLayerValues(longitude: number, latitude: number) {
  const temp = 16 - Math.abs(latitude - 51) * 0.55 + Math.sin(longitude / 7) * 3;
  const wind = 5 + Math.abs(Math.cos(latitude / 6) * 8);
  const precip = Math.max(0, Math.sin((longitude + latitude) / 5) * 6);
  return [
    { label: "Mock temperature", value: temp.toFixed(1), unit: "degC", status: "mock" as const },
    { label: "Mock wind", value: wind.toFixed(1), unit: "m/s", status: "mock" as const },
    { label: "Mock radar precip", value: precip.toFixed(1), unit: "mm/h", status: "mock" as const }
  ];
}
